version: '3'
services:
  mysql:
    image: ${MYSQL_IMAGE:-percona/percona-server}
    ports:
      - 127.0.0.1:3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command:
      - --socket=/tmp/pmm-test/mysql.sock
    volumes:
      - /tmp/pmm-test:/tmp/pmm-test
