[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/shirou/gopsutil"
  branch = "master"

[[constraint]]
  name = "github.com/mattetti/filebuffer"
  version = "1.0.0"
